import assert from 'node:assert/strict';
import fs from 'node:fs';
import {availableCastSlots, spellRollPlan, criticalDice, exhaustionLevel} from '../src/lib/casting.js';
const spells=JSON.parse(fs.readFileSync(new URL('../src/data/spells.json',import.meta.url),'utf8'));
const plan=(index,slot,level,modifier=3)=>spellRollPlan(spells.find(s=>s.index===index),slot,level,modifier);
assert.equal(plan('fireball',5,9).damage[0].expression,'10d6');
assert.equal(plan('fire-bolt',0,11).damage[0].expression,'3d10');
assert.equal(plan('eldritch-blast',0,17).attacks,4);
assert.equal(plan('scorching-ray',4,7).attacks,5);
assert.equal(plan('scorching-ray',4,7).damage[0].expression,'2d6');
assert.equal(plan('cure-wounds',2,3).healing,'2d8+3');
assert.equal(plan('cure-wounds',1,1,-1).healing,'1d8-1');
assert.deepEqual(availableCastSlots(1,[0,0,2],{3:1}),[{level:3,remaining:1}]);
assert.deepEqual(availableCastSlots(1,[2],{1:2}),[]);
assert.deepEqual(availableCastSlots(3,[4,3,0,1],{}),[{level:4,remaining:1}]);
assert.equal(criticalDice('1d8+3'),'2d8+3');
assert.equal(exhaustionLevel({conditions:'Poisoned, Exhaustion'}),1);
assert.equal(exhaustionLevel({exhaustion:3}),3);
assert.equal(exhaustionLevel({exhaustion:9}),6);
assert.equal(exhaustionLevel({exhaustion:0,conditions:[]}),0);
console.log('PASS casting slots, spell scaling, rays, healing, critical dice and exhaustion migration');
