import assert from 'node:assert/strict';
import {createServer} from 'vite';
import fs from 'node:fs';
const server=await createServer({server:{middlewareMode:true},optimizeDeps:{noDiscovery:true,include:[]}});
try {
 const e=await server.ssrLoadModule('/src/lib/editions.js');
 const p=await server.ssrLoadModule('/src/lib/play.js');
 const {effectiveAbilities}=await server.ssrLoadModule('/src/CharacterManager.jsx');
 const wizard={ruleset:'2024',className:'Wizard',level:1,speed:30,hp:{max:21,current:21},abilities:{str:10,dex:12,con:14,int:16,wis:10,cha:8},abilityBonuses:{int:2},spells:[]};
 assert.equal(e.characterSlots(wizard)[1],2);
 assert.deepEqual(e.spellCounts(wizard),{cantrips:3,known:6,prepared:4,mode:'spellbook'});
 assert.equal(e.characterSlots({...wizard,className:'Ranger'})[1],2);
 assert.equal(e.characterSlots({...wizard,ruleset:'2014',className:'Ranger'})[1],0);
 assert.equal(effectiveAbilities({...wizard,race:'Elf'}).int,18);
 assert.equal(effectiveAbilities({...wizard,race:'Elf'}).dex,12);
 assert(e.classFeatures(wizard).some(f=>f.name==='Ritual Adept'));
 assert(!e.classFeatures(wizard).some(f=>f.name==='Scholar'));
 assert(e.classFeatures({...wizard,level:2}).some(f=>f.name==='Scholar'));
 const spell=(name,edition='2024')=>e.allSpells.find(s=>s.name===name&&s.edition===edition);
 assert.equal(p.spellPlan(spell('Cure Wounds'),wizard,3,3).rolls[0].expression,'6d8+3');
 assert.equal(p.spellPlan(spell('Healing Word'),wizard,2,-1).rolls[0].expression,'4d4-1');
 assert.equal(p.spellPlan(spell('Fire Bolt'),{...wizard,level:11},0,3).rolls[0].expression,'3d10');
 assert.equal(p.spellPlan(spell('Scorching Ray'),wizard,4,3).count,5);
 assert.equal(p.spellPlan(spell('Eldritch Blast'),{...wizard,level:17},0,3).count,4);
 assert.equal(p.spellPlan(spell('Fireball'),wizard,5,3).rolls[0].expression,'10d6');
 assert.equal(p.conditionEffects({...wizard,exhaustion:3}).penalty,-6);
 assert.equal(p.conditionEffects({...wizard,exhaustion:3}).speed,15);
 assert.equal(p.conditionEffects({...wizard,ruleset:'2014',exhaustion:4}).maxHP,10);
 assert.equal(p.conditionEffects({...wizard,ruleset:'2014',exhaustion:3}).attackDisadvantage,true);
 assert.equal(p.conditionEffects({...wizard,conditions:['',' poisoned ']}).checkDisadvantage,true);
 assert.equal(p.exhaustionLevel({conditions:'exhaustion'}),1);
 assert.equal(p.exhaustionLevel({exhaustion:2.9}),2);
 assert.equal(p.rollMode('advantage',true),'normal');
 const legacy={...wizard,ruleset:'3.5',className:'Fighter',level:6};
 assert.deepEqual(e.legacyProgression(legacy),{bab:6,fort:5,ref:2,will:2});
 assert.equal(e.characterSlots(legacy).reduce((a,b)=>a+b),0);
 const legacyCaster={...wizard,ruleset:'3.5',mechanics:'3.5',className:'Archivist',level:4,classDefinition:{name:'Archivist',edition:'3.5',catalogId:'dndtools:classes/archivist-74'},classSpellSlots:[{sourceClassId:'dndtools:classes/archivist-74',sourceClassName:'Archivist',slots:[4,4,3,0,0,0,0,0,0,0]}]};
 assert.deepEqual(e.characterSlots(legacyCaster).slice(0,4),[4,4,3,0]);
 assert.equal(e.spellSlotPools(legacyCaster).mode,'automatic');
 assert.equal(p.conditionEffects({...legacy,exhaustion:6}).dead,false);
 const cross={...wizard,ruleset:'custom',mechanics:'2024',classDefinition:{name:'Wizard',edition:'3.5'}};
 assert.equal(e.characterSlots(cross).reduce((a,b)=>a+b),0);
 const names=e.permittedSpells({...cross,unrestrictedSpellAccess:true}).filter(s=>s.name==='Magic Missile');
 assert.equal(new Set(names.map(e.keyOf)).size,3);
 const reference={category:'spell',edition:'3.5',name:'Reference spell',catalogId:'source:123',level:null,classes:[],referenceOnly:true};
 assert(!e.permittedSpells(legacy,[reference]).some(s=>e.keyOf(s)==='source:123'));
 assert.deepEqual(p.availableSlots({...legacy,slotOverride:[2,0,0],slotsUsed:{0:1}},{level:0}),[{level:0,remaining:1}]);
 assert.equal(p.spellPlan(reference,legacy,1,2).rolls.length,0);
 assert.throws(()=>e.validPack([{category:'spell',edition:'custom',name:'Invalid',description:'x',level:10,classes:[]}]),/level/);
 assert.notEqual(e.keyOf({id:'a',name:'Same',edition:'custom'}),e.keyOf({id:'b',name:'Same',edition:'custom'}));
 console.log('PASS edition slots, spell selection, scaling, progression, exhaustion and cross-edition identities');
 const manifest=JSON.parse(fs.readFileSync('public/catalogs/dndtools/manifest.json'));
 assert.equal(manifest.complete,true);assert.equal(manifest.categories.length,14);
 let total=0;for(const category of manifest.categories){const rows=JSON.parse(fs.readFileSync(`public/catalogs/dndtools/${category.id}.json`));assert.equal(rows.length,category.count);assert.equal(category.count,category.sourceCount);assert.equal(new Set(rows.map(r=>r.id)).size,rows.length);assert(rows.every(r=>r.name&&r.url.startsWith(`https://new.dndtools.org/${category.id}/`)));total+=rows.length;}
 assert.equal(manifest.categories.find(c=>c.id==='spells').count,5035);
 assert.equal(manifest.categories.find(c=>c.id==='classes').count,1054);
 console.log(`PASS ${total} verified source references across all 14 categories`);
} finally {await server.close();}
