import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {createServer} from 'vite';
const server=await createServer({server:{middlewareMode:true},optimizeDeps:{noDiscovery:true,include:[]}});
try{
 const f=await server.ssrLoadModule('/src/lib/featMagic.js'),b=await server.ssrLoadModule('/src/lib/backgroundFeats.js'),casting=await server.ssrLoadModule('/src/lib/featCasting.js'),{recordedTraining}=await server.ssrLoadModule('/src/lib/training.js');
 const c={ruleset:'2024',className:'Fighter',level:4,abilities:{str:14,dex:14,con:14,int:16,wis:16,cha:14},feats:[],spells:[]};
 for(const [background,list] of [['Sage','Wizard'],['Acolyte','Cleric']]){const feat=b.backgroundFeat({...c,background});assert.equal(feat.requiredSpellList,list);assert.equal(feat.edition,'2024');const configured={...feat,magicChoices:{list,ability:'wis',cantrips:list==='Wizard'?['2024:mage-hand','2024:light']:['2024:guidance','2024:light'],spell:list==='Wizard'?'2024:shield':'2024:bless'}};assert(f.featMagicState(configured,c).valid);assert.deepEqual(b.setupBackgroundFeats({...c,background,feats:[configured]})[0].magicChoices,configured.magicChoices);assert.equal(b.setupBackgroundFeats({...c,background:'Soldier',feats:[configured]})[0].name,'Savage Attacker');}
 const initiate={id:'mi',name:'Magic Initiate',edition:'2024',level:4,magicChoices:{list:'Wizard',ability:'int',cantrips:['2024:mage-hand','2024:light'],spell:'2024:shield'}};
 const changed={...initiate,magicChoices:{...initiate.magicChoices,spell:'2024:magic-missile'}};
 assert.throws(()=>f.changeFeatChoices(c,initiate,changed));const accepted=f.changeFeatChoices({...c,level:5},initiate,changed);assert.equal(accepted.magicChoices.changedLevel,5);assert.throws(()=>f.changeFeatChoices({...c,level:5},accepted,initiate));
 assert.throws(()=>f.changeFeatChoices({...c,level:5},initiate,{...changed,magicChoices:{...changed.magicChoices,ability:'cha'}}));assert.equal(f.changeFeatChoices(c,initiate,changed,{correctionReason:'Corrected imported choice'}).magicCorrections.length,1);
 for(const edition of ['2014','2024'])for(const name of ['Telekinetic','Telepathic']){const feat={id:name,name,edition,magicChoices:{ability:'int'}},char={...c,ruleset:edition,feats:[feat]};assert(f.featMagicState(feat,char).valid);assert.equal(f.featMagicSpells(char).length,1);assert.equal(f.applyFeatAbilityIncrease(char,'int',16),17);assert.equal(f.featMagicSpells(char)[0].name,name==='Telekinetic'?'Mage Hand':'Detect Thoughts');}
 for(const edition of ['2014','2024']){const feat={id:'ritual',name:'Ritual Caster',edition,magicChoices:{list:'Wizard',ability:'wis',spells:[`${edition}:detect-magic`,`${edition}:find-familiar`]}},char={...c,level:4,ruleset:edition,feats:[feat]},spells=f.featMagicSpells(char);assert.equal(spells.length,2);assert(casting.featCastOptions(char,spells[0]).some(x=>x.pool==='ritual'));const spend=casting.spendFeatCast(char,spells[0],{pool:'ritual',level:1});assert.deepEqual(spend,{});if(edition==='2024'){const next={...char,...casting.spendFeatCast(char,spells[0],{pool:'feat',level:1})};assert(!casting.featCastOptions(next,spells[1]).some(x=>x.pool==='feat'));assert(f.featMagicState(feat,{...char,level:5}).valid);assert(!f.featMagicState(feat,{...char,level:5}).complete);}else assert(!casting.featCastOptions(char,spells[0]).some(x=>x.pool==='feat'));}
 const external={catalogId:'published:artificer-cantrip',category:'spell',name:'Published cantrip',edition:'2014',level:0,classes:['Artificer'],school:'Transmutation',description:'A reviewed spell.',sourceUrl:'https://example.org/rules'},leveled={...external,catalogId:'published:artificer-spell',name:'Published spell',level:1};
 const artificer={id:'ai',name:'Artificer Initiate',edition:'2014',magicChoices:{list:'Artificer',cantrips:[external.catalogId],spell:leveled.catalogId,tool:f.artisanTools[0],entries:{[external.catalogId]:external,[leveled.catalogId]:leveled}}};
 assert(f.featMagicState(artificer,c).valid);assert.equal(recordedTraining({...c,feats:[artificer]})[0].name,f.artisanTools[0]);assert(!f.featMagicState({...artificer,magicChoices:{...artificer.magicChoices,entries:{}}},c).valid);assert.equal(f.featMagicOptions({...artificer,magicChoices:{...artificer.magicChoices,entries:{}}},c,[{...external,referenceOnly:true}]).cantrips.length,0);
 const sniper={id:'ss',name:'Spell Sniper',edition:'2014',magicChoices:{list:'Wizard',cantrips:['2014:fire-bolt']}};assert(f.featMagicState(sniper,c).valid);assert(!f.featMagicState({...sniper,magicChoices:{list:'Wizard',cantrips:['2014:mage-hand']}},c).valid);
 const rituals=await server.ssrLoadModule('/src/lib/ritualCasting.js'),e=await server.ssrLoadModule('/src/lib/editions.js');
 const ritual={id:'r',name:'Ritual Caster',edition:'2014',magicChoices:{list:'Wizard',spells:['2014:detect-magic','2014:find-familiar']}};
 const unseen=f.featSpellCatalog(ritual,c).find(s=>s.name==='Unseen Servant'),copied=f.copyFeatRitual(ritual,c,unseen,'Found spellbook');assert.equal(f.featMagicState(copied,c).spells.length,3);assert.throws(()=>f.copyFeatRitual(copied,c,unseen,'Book'));assert.throws(()=>f.copyFeatRitual(ritual,c,unseen,''));assert.throws(()=>f.copyFeatRitual(ritual,c,{...unseen,catalogId:'fabricated',referenceOnly:true},'Book'));
 const r24={id:'r24',name:'Ritual Caster',edition:'2024',magicChoices:{ability:'int',spells:['2024:detect-magic','2024:find-familiar']}};
 const wizard={...c,className:'Wizard',level:4,feats:[r24]},silence={...e.allSpells.find(s=>s.name==='Silence'&&s.edition==='2024'),prepared:true};
 const cleric={...wizard,className:'Cleric'};assert(rituals.quickRitualOption(cleric,silence));assert(!rituals.quickRitualOption(wizard,silence));assert(!rituals.quickRitualOption(cleric,{...silence,prepared:false}));const used={...cleric,...rituals.spendQuickRitual(cleric,silence)};assert(!rituals.quickRitualOption(used,silence));assert(!casting.featCastOptions(used,f.featMagicSpells(used)[0]).some(x=>x.pool==='feat'));
 const detect=e.allSpells.find(s=>s.name==='Detect Magic'&&s.edition==='2014');assert(rituals.canClassRitual({...wizard,ruleset:'2014'},detect));assert(!rituals.canClassRitual({...wizard,ruleset:'2014',className:'Sorcerer'},detect));assert(!rituals.canClassRitual({...wizard,ruleset:'2014',className:'Cleric'},detect));assert(rituals.canClassRitual({...wizard,ruleset:'2014',className:'Cleric'},{...detect,prepared:true}));
 assert(!f.featMagicState({...initiate,magicChoices:{cantrips:{},spells:{}}},c).valid);
 console.log('PASS background choices, published feat spells, Artificer/Spell Sniper/Telekinetic/Telepathic/Ritual Caster, shared Quick Ritual, level-only replacements and correction history');
}finally{await server.close();}
