import assert from 'node:assert/strict';
import {hitDicePools,needsHitDiceReview,recoveryLimit,defaultRecovery,setSpentHitDice,spendHitDice,recoverHitDice} from '../src/lib/hitDice.js';
import {advanceClass} from '../src/lib/advancement.js';
const make=(edition='2014')=>({ruleset:edition,level:5,className:'Fighter',hitDie:'d10',hp:{current:10,max:40},abilities:{str:16,int:16},classLevels:[{catalogId:'fighter',name:'Fighter',edition,level:3,definition:{hit_die:10}},{catalogId:'wizard',name:'Wizard',edition,level:2,definition:{hit_die:6}}]});
let c=make();
assert.deepEqual(hitDicePools(c).map(p=>[p.sides,p.total,p.available]),[[10,3,3],[6,2,2]]);
const expressions=[];
let result=spendHitDice(c,{fighter:1,wizard:2},2,(expression,label,options)=>{expressions.push(expression);assert.equal(options.kind,'healing');return {total:3};});
assert.deepEqual(expressions,['1d10','1d6','1d6']);assert.equal(result.healing,15);
assert.deepEqual(result.hitDiceUsedByClass,{fighter:1,wizard:2});assert.equal(result.hitDiceUsed,3);
assert.equal(c.hitDiceUsedByClass,undefined,'Input remains immutable');
c={...c,...result};
assert.equal(recoveryLimit(c),2,'Odd levels round down');
assert.deepEqual(defaultRecovery(c),{fighter:1,wizard:1});
assert.deepEqual(recoverHitDice(c,{wizard:2}),{hitDiceUsedByClass:{fighter:1,wizard:0},hitDiceUsed:1});
assert.throws(()=>recoverHitDice(c,{fighter:1,wizard:2}),/Too many/);
assert.deepEqual(recoverHitDice({...c,ruleset:'2024'}),{hitDiceUsedByClass:{fighter:0,wizard:0},hitDiceUsed:0});
for(const selection of [{fighter:3},{wizard:1},{fighter:-1},{fighter:0.5},{unknown:1},{fighter:NaN}])assert.throws(()=>spendHitDice(c,selection,2,()=>{throw Error('Should not roll');}),/whole hit dice/);
assert.equal(spendHitDice(make(),{fighter:1},-5,()=>({total:1})).healing,0);
assert.equal(spendHitDice(make(),{fighter:1},2,()=>null).hitDiceUsed,0,'Failed rolls spend nothing');
assert.equal(spendHitDice(make(),{},2,()=>{throw Error('No selection should not roll');}).healing,0);
const old={ruleset:'2014',className:'Fighter',level:3,hitDie:'d10',hitDiceUsed:2,hp:{max:25,current:10}};
assert.equal(hitDicePools(old)[0].used,2);assert(!needsHitDiceReview(old));
const record={name:'Wizard',catalogId:'wizard',edition:'2014',hit_die:6,multi_classing:{prerequisites:[{ability_score:{index:'int'},minimum_score:13}]}};
const qualifiedOld={...old,abilities:{str:16,int:16},classDefinition:{name:'Fighter',catalogId:'fighter',edition:'2014',hit_die:10,multi_classing:{prerequisites:[{ability_score:{index:'str'},minimum_score:13}]}}};
const advanced=advanceClass(qualifiedOld,record,{hpGain:4});
assert.deepEqual(hitDicePools(advanced).map(p=>p.used),[2,0],'New class does not inherit old expenditure');
assert.equal(recoveryLimit({...old,level:1}),1);
const ambiguous={...make(),hitDiceUsed:4};
assert(needsHitDiceReview(ambiguous));assert.deepEqual(hitDicePools(ambiguous).map(p=>p.used),[3,1]);
assert.throws(()=>spendHitDice(ambiguous,{},0,()=>({total:1})),/Review/);
assert.throws(()=>recoverHitDice(ambiguous),/Review/);
const corrected={...ambiguous,...setSpentHitDice(ambiguous,{fighter:2,wizard:2})};
assert(!needsHitDiceReview(corrected));assert.equal(corrected.hitDiceUsed,4);
assert.throws(()=>setSpentHitDice(corrected,{wizard:3}),/whole hit dice/);
const increased={...corrected,classLevels:corrected.classLevels.map(p=>p.catalogId==='fighter'?{...p,level:4}:p)};
assert.deepEqual(hitDicePools(increased).map(p=>[p.used,p.available]),[[2,2],[2,0]]);
const missing=make();delete missing.classLevels[1].definition.hit_die;
assert.equal(hitDicePools(missing)[1].sides,null);
assert.throws(()=>spendHitDice(missing,{wizard:1},0,()=>({total:1})),/source/);
assert.equal(recoverHitDice({...corrected,ruleset:'custom',mechanics:'2024'}).hitDiceUsed,0);
console.log('PASS per-class hit dice, bounded spending, Constitution healing, chosen 2014/all 2024 recovery, legacy migration and advancement');
