import assert from 'node:assert/strict';
import {createServer} from 'vite';
import {createCloudStorage} from '../src/lib/storage.js';
const server=await createServer({server:{middlewareMode:true}});
try {
 const r=await server.ssrLoadModule('/src/lib/rules.js');
 assert.equal(r.spellCatalog.length,319);
 assert.equal(r.maxSpellLevel('Paladin',1),0);
 assert.equal(r.maxSpellLevel('Paladin',2),1);
 assert.equal(r.maxSpellLevel('Paladin',5),2);
 assert.equal(r.maxSpellLevel('Ranger',5),2);
 assert.equal(r.maxSpellLevel('Wizard',17),9);
 assert.deepEqual(r.slotsFor('Warlock',5),[0,0,2,0,0,0,0,0,0]);
 assert.equal(r.countsFor('Ranger',2,14).known,2);
 assert.equal(r.countsFor('Cleric',4,18).prepared,8);
 assert.equal(r.countsFor('Wizard',4,18).known,12);
 assert.deepEqual(r.changeHP({current:12,max:20,temp:5},7),{current:10,max:20,temp:0});
 assert.equal(r.changeHP({current:12,max:20,temp:0},99,true).current,20);
 let stream=[0,0.99];assert.equal(r.rollDice('1d20+3','advantage',()=>stream.shift()).total,23);
 stream=[0,0.99];assert.equal(r.rollDice('1d20+3','disadvantage',()=>stream.shift()).total,4);
 assert.throws(()=>r.rollDice('Infinityd20'));
 assert.throws(()=>r.rollDice('0d20'));
 const fighter={className:'Fighter',level:1,inventory:[{id:'a',equipmentIndex:'chain-mail',equipped:true},{id:'b',equipmentIndex:'shield',equipped:true},{id:'c',name:'Longsword',equipmentIndex:'longsword',equipped:true}]};
 assert.equal(r.armorFor(fighter,{str:16,dex:14,con:14,wis:10}),18);
 assert.equal(r.weaponAttacks(fighter,{str:16,dex:14})[0].attack,5);
 console.log('PASS spell progression, pact slots, dice, HP, armor and weapon calculations');
 const rows=[];let fail=false;const query={from(table){assert.equal(table,'characters');const filters=[];const api={select(){return api;},eq(k,v){filters.push(x=>x[k]===v);return api;},neq(k,v){filters.push(x=>x[k]!==v);return api;},order(){return api;},maybeSingle(){api.single=true;return api;},then(resolve){const found=rows.filter(x=>filters.every(fn=>fn(x)));resolve({data:api.single?found[0]||null:found,error:fail?new Error('Offline'):null});},async upsert(row,options){assert.equal(options.onConflict,'user_id,id');if(fail)return {error:new Error('Offline')};const existing=rows.findIndex(x=>x.user_id===row.user_id&&x.id===row.id);if(existing<0)rows.push(row);else rows[existing]=row;return {error:null};},delete(){api.then=resolve=>{for(let i=rows.length-1;i>=0;i--)if(filters.every(fn=>fn(rows[i])))rows.splice(i,1);resolve({error:null});};return api;}};return api;}};
 const a=createCloudStorage(query,'owner-a'),b=createCloudStorage(query,'owner-b');
 await a.set('char-detail:hero',JSON.stringify({id:'hero',name:'A',level:2}));
 await b.set('char-detail:hero',JSON.stringify({id:'hero',name:'B',level:1}));
 await a.set('char-detail:ledger-workspace',JSON.stringify({id:'ledger-workspace',name:'workspace',campaigns:[{name:'Campaign'}]}));
 assert.equal(JSON.parse((await a.get('char-detail:hero')).value).name,'A');
 assert.equal(JSON.parse((await b.get('char-detail:hero')).value).name,'B');
 assert.equal(JSON.parse((await a.get('char-index')).value).length,1);
 assert.equal(JSON.parse((await a.get('char-detail:ledger-workspace')).value).campaigns[0].name,'Campaign');
 fail=true;await assert.rejects(a.set('char-detail:hero','{}'));fail=false;
 await a.delete('char-detail:hero');assert.equal(await a.get('char-detail:hero'),null);
 assert.equal(JSON.parse((await b.get('char-detail:hero')).value).name,'B');
 console.log('PASS cloud adapter round trips, owner filtering, workspace separation and error propagation');
} finally {await server.close();}
