import React,{useState,useEffect} from 'react';
import {modern,legacy,keyOf,editionName} from './lib/editions';
import feats14 from './data/feats.json';
import {useReferenceIndex} from './lib/referenceIndex';
import {requirements,qualified} from './lib/advancement';
import Requirements from './Requirements';
export default function FeatChoices({char,patch,homebrew=[],editable=false}) {
 const [open,setOpen]=useState(false),[query,setQuery]=useState(''),[page,setPage]=useState(0),[confirmations,setConfirmations]=useState({}),[custom,setCustom]=useState('');
 const reference=useReferenceIndex(open?['feats']:[],char.ruleset||'2014');
 useEffect(()=>setPage(0),[query]);
 const candidates=[...feats14.map(f=>({...f,edition:'2014'})),...modern.feats.map(f=>({...f,edition:'2024'})),...(legacy.feats||[]),...homebrew.filter(f=>f.category==='feat'),...reference.entries].filter(f=>(char.ruleset==='custom'||f.edition===(char.ruleset||'2014'))&&f.name.toLowerCase().includes(query.toLowerCase()));
 return <section aria-label="Feat choices"><h3>Review feat selections</h3>{editable&&(char.feats||[]).map(f=><div className="feature-detail" key={f.id||keyOf(f)}><strong>{f.name}</strong><p>{f.description||f.desc?.join('\n')}</p><button className="l-button" onClick={()=>patch({feats:char.feats.filter(x=>x!==f)})}>Remove {f.name}</button></div>)}
 <button className="l-button" onClick={()=>setOpen(!open)}>{open?'Close feat catalog':'Choose from feat catalog'}</button>{open&&<div className="l-panel"><label className="l-field"><span>Search feats</span><input value={query} onChange={e=>setQuery(e.target.value)}/></label><p>Choose feats only when your class, race or table grants a feat. Ability changes and choice-dependent benefits must be recorded on your sheet.</p>{reference.loading&&<p role="status">Loading feats…</p>}{reference.error&&<p role="alert">{reference.error}<button className="l-button" onClick={reference.retry}>Retry catalog</button></p>}
 {candidates.slice(page*20,page*20+20).map(f=>{const selected=(char.feats||[]).some(x=>keyOf(x)===keyOf(f)),checks=requirements(f,char,confirmations),damaged=!!f.integrityIssues?.length;return <details className="feature-detail" key={keyOf(f)} data-catalog-id={keyOf(f)}><summary>{f.name} · {editionName(f.edition)} · {f.sourceBook||f.source||'SRD'}</summary><p className="preserve-lines">{f.description||f.desc?.join('\n')}</p>{damaged&&<p role="alert">This source entry has an invalid effect extract and is unavailable until repaired. Use a verified source to create a separate homebrew entry.</p>}{f.sourceUrl&&<p><a href={f.sourceUrl} target="_blank" rel="noreferrer">Read source</a></p>}<Requirements checks={checks} confirmations={confirmations} onConfirm={setConfirmations}/><button className="l-button" disabled={selected||damaged||!qualified(checks)} onClick={()=>patch({feats:[...(char.feats||[]),{...f,catalogId:keyOf(f),id:crypto.randomUUID(),level:char.level,prerequisiteConfirmations:confirmations}]})}>{selected?'Added':'Add feat'}</button></details>;})}
 <div className="l-toolbar"><button className="l-button" disabled={!page} onClick={()=>setPage(page-1)}>Previous</button><span>{candidates.length} feats · Page {page+1}</span><button className="l-button" disabled={(page+1)*20>=candidates.length} onClick={()=>setPage(page+1)}>Next</button></div>
 <label className="l-field"><span>Custom feat name</span><input value={custom} onChange={e=>setCustom(e.target.value)}/></label><button className="l-button" disabled={!custom.trim()} onClick={()=>{patch({feats:[...(char.feats||[]),{id:crypto.randomUUID(),name:custom.trim(),description:'',source:'Homebrew',level:char.level}]});setCustom('');}}>Add custom feat</button></div>}</section>;
}
