import ClassFeatureChoices from './ClassFeatureChoices';
import {featureChoicePlan,applyFeatureChoices} from './lib/featureChoices';
import React,{useState,useEffect,useRef} from 'react';
import { ABILITIES,SKILLS,RACE_DATA,CLASS_DATA,BACKGROUND_DATA,blankCharacter,effectiveAbilities,syncProgression } from './CharacterManager';
import { classes,modifier,armorFor,subclasses } from './lib/rules';
import { editions,editionName,modern,legacy,mechanics,is35,keyOf,spellCounts,permittedSpells,characterSlots,levelRecord,legacyProgression } from './lib/editions';
import subraces from './data/subraces.json';
import LanguageChoices from './LanguageChoices';
import ClassProgression from './ClassProgression';
import {languagePlan,chosenLanguages} from './lib/languages';
import {rollDice} from './lib/rules';
import traits14 from './data/traits.json';
import equipment from './data/equipment.json';
import EquipmentChoice,{resolveEquipment} from './StartingEquipment';
import SpellPicker from './EditionSpellPicker';
import {useReferenceIndex} from './lib/referenceIndex';
import {prestige,normalizeAdvancement,requirements,qualified} from './lib/advancement';
import FeatChoices from './FeatChoices';
import CatalogItems from './CatalogItems';
import {coreClassSkillOptions} from './lib/training';
const uid=()=>crypto.randomUUID();
const basicScores={str:15,dex:14,con:13,int:12,wis:10,cha:8};
const cost={8:0,9:1,10:2,11:3,12:4,13:5,14:7,15:9};
export function classOptions(edition,homebrew=[]){
 const canonical=homebrew.filter(x=>x.category==='class'), published=canonical.filter(x=>x.edition==='2014'&&x.enrichment);
 const base=[...classes.filter(c=>!published.some(p=>p.name===c.name)).map(c=>({...c,edition:'2014',description:CLASS_DATA[c.name]?.blurb||''})),...modern.classes.map(c=>({...c,edition:'2024',description:CLASS_DATA[c.name]?.blurb||''})),...legacy.classes];
 const extra=canonical.map(c=>{const srd=c.edition==='2014'&&c.enrichment?classes.find(x=>x.name===c.name):null;
 return {...srd,...c,index:c.index||c.id,hit_die:c.hit_die||srd?.hit_die||null,saving_throws:srd?.saving_throws||c.saving_throws,proficiency_choices:srd?.proficiency_choices||c.proficiency_choices,starting_equipment:srd?.starting_equipment||c.starting_equipment,starting_equipment_options:srd?.starting_equipment_options||c.starting_equipment_options,supplementSource:srd?'SRD 5.1 starting equipment and proficiency choices':undefined};});
 return [...base,...extra].filter(c=>edition==='custom'||c.edition===edition);
}
export function raceOptions(edition,homebrew=[]){return [...Object.entries(RACE_DATA).map(([name,d])=>({...d,index:name,name,edition:'2014',speed:parseInt(d.speed),description:d.blurb,traits:d.traits.map(([name,description])=>({name,description}))})),...modern.species.map(s=>({...s,edition:'2024',description:`${s.size} · ${s.type}`,bonuses:{},traits:s.traits.map(t=>modern.traits.find(x=>x.index===t.index)||t)})),...legacy.races,...homebrew.filter(x=>x.category==='race').map(r=>({...r,index:r.id,speed:r.speed??30,traits:[{name:r.name,description:r.description}]}))].filter(r=>edition==='custom'||r.edition===edition);}
function Field({label,children}){return <label className="creation-field"><span>{label}</span>{children}</label>;}
function Picks({options,value,onChange,kind}){const [search,setSearch]=useState(''),[edition,setEdition]=useState('all'),[page,setPage]=useState(0);useEffect(()=>setPage(0),[search,edition]);const visible=options.filter(o=>o.name.toLowerCase().includes(search.toLowerCase())&&(edition==='all'||o.edition===edition));return <><div className="spell-filters"><Field label={`Search ${kind}`}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={`Find a ${kind}…`}/></Field><Field label="Content edition"><select value={edition} onChange={e=>setEdition(e.target.value)}><option value="all">All available editions</option>{editions.map(([id,n])=><option key={id} value={id}>{n}</option>)}</select></Field></div><div className="creation-grid three">{visible.slice(page*18,page*18+18).map(o=><button type="button" className={`creation-choice ${value===keyOf(o)?'is-selected':''}`} aria-pressed={value===keyOf(o)} key={keyOf(o)} data-catalog-id={keyOf(o)} onClick={()=>onChange(o)}><span className="creation-choice-title">{o.name}</span><span className="l-tag">{editionName(o.edition)}{o.prestige?' · Prestige':''}</span><small>{kind==='class'?o.referenceOnly?'Source reference':`d${o.hit_die||8} hit die`:o.speed?`${o.speed} ft. speed`:''}</small><small>{o.sourceBook||o.source||'SRD'}</small><p>{(o.description||'Homebrew option').slice(0,95)}{o.description?.length>95?'…':''}</p></button>)}</div><div className="l-toolbar pager"><button className="l-button" disabled={!page} onClick={()=>setPage(page-1)}>Previous</button><span>{visible.length} options · Page {page+1}</span><button className="l-button" disabled={(page+1)*18>=visible.length} onClick={()=>setPage(page+1)}>Next</button></div>{!visible.length&&<p>No matching options. Add one in Homebrew, or clear the filters.</p>}</>;}
export function focusDialog(ref){return ()=>{const root=ref.current,old=document.activeElement;root?.querySelector('input,button')?.focus();const key=e=>{if(e.key!=='Tab')return;const list=[...root.querySelectorAll('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea,a[href]')].filter(x=>x.getClientRects().length);if(!list.length)return;if(e.shiftKey&&document.activeElement===list[0]){e.preventDefault();list.at(-1).focus();}if(!e.shiftKey&&document.activeElement===list.at(-1)){e.preventDefault();list[0].focus();}};root?.addEventListener('keydown',key);return()=>{root?.removeEventListener('keydown',key);old?.focus();};};}
export default function GuidedSetup({onCancel,onFinish,homebrew:customEntries=[],onRoll=expression=>rollDice(expression)}){
 const [step,setStep]=useState(0),[draft,setDraft]=useState({ruleset:'2014',mechanics:'2014',name:'',className:'',race:'',background:'',level:1,abilities:basicScores,classSkills:[],bonusSkills:[],spellIds:[],cantripIds:[],gear:{},bgGear:{},subrace:'',subclass:'',method:'standard',bonusA:'',bonusB:'',bonusMode:'two',bonusC:'',notes:''});
 const reference=useReferenceIndex(step===1?['classes']:step===2?['races']:step===6?['spells']:[],draft.ruleset),homebrew=[...customEntries,...reference.entries];
 const shell=useRef(null);useEffect(focusDialog(shell),[]);useEffect(()=>{shell.current?.querySelector('.creation-scroll')?.scrollTo(0,0);},[step]);
 const patch=v=>setDraft(d=>({...d,...v})),rules=mechanics(draft),c=draft.classDefinition,r=draft.raceDefinition;
 const bg=rules==='2024'?modern.backgrounds.find(x=>x.name===draft.background):BACKGROUND_DATA[draft.background];
 const classList=classOptions(draft.ruleset,homebrew).filter(c=>!prestige(c)),raceList=raceOptions(draft.ruleset,homebrew);
 const subOptions=r?.edition==='2024'?modern.subspecies.filter(s=>r.subspecies?.some(x=>x.index===s.index)):r?.edition==='2014'?subraces.filter(s=>s.race.name===r.name):[];
 const sub=subOptions.find(s=>s.name===draft.subrace);
 const bonuses={...(r?.bonuses||{})};for(const b of sub?.ability_bonuses||[])bonuses[b.ability_score.index]=(bonuses[b.ability_score.index]||0)+b.bonus;
 const originBonus=rules==='2024';const halfElf=r?.edition==='2014'&&r.name==='Half-Elf';
 if(originBonus){for(const k of Object.keys(bonuses))delete bonuses[k];if(draft.bonusA)bonuses[draft.bonusA]=draft.bonusMode==='two'?2:1;if(draft.bonusB)bonuses[draft.bonusB]=(bonuses[draft.bonusB]||0)+1;if(draft.bonusMode==='three'&&draft.bonusC)bonuses[draft.bonusC]=(bonuses[draft.bonusC]||0)+1;}
 else if(halfElf){if(draft.bonusA)bonuses[draft.bonusA]=(bonuses[draft.bonusA]||0)+1;if(draft.bonusB)bonuses[draft.bonusB]=(bonuses[draft.bonusB]||0)+1;}
 const totals=Object.fromEntries(ABILITIES.map(a=>[a.key,Number(draft.abilities[a.key])+(bonuses[a.key]||0)]));
 const counts=spellCounts(draft,totals[draft.castingAbility||({Bard:'cha',Cleric:'wis',Druid:'wis',Paladin:'cha',Ranger:'wis',Sorcerer:'cha',Warlock:'cha',Wizard:'int'}[draft.className])]||10);
 const spells=permittedSpells(draft,homebrew),manual=is35(draft)||draft.ruleset==='custom',spellLimit=manual?Infinity:counts.mode==='spellbook'?counts.known:counts.mode==='known'?counts.known:counts.prepared;
 const cantripLimit=manual?Infinity:counts.cantrips;
 const skillOptions=coreClassSkillOptions(c)||c?.proficiency_choices?.[0]?.from?.options?.map(x=>(x.item?.name||'').replace('Skill: ','')).filter(Boolean)||SKILLS.map(x=>x[0]);
 const skillLimit=c?.proficiency_choices?.[0]?.choose||0;
 const bgSkills=rules==='2024'?(bg?.proficiencies||[]).filter(x=>x.index.startsWith('skill-')).map(x=>x.name.replace('Skill: ','')):(bg?.skills||'').split(',').map(x=>x.trim()).filter(Boolean);
 const languageRules=languagePlan(draft,totals.int),languages=chosenLanguages(languageRules,draft.languageChoices);
 const featureDraft={...draft,skillProf:Object.fromEntries([...bgSkills,...draft.classSkills,...(draft.bonusSkills||[])].map(n=>[n,true]))};
 const featurePlan=featureChoicePlan(featureDraft,null,draft.featurePicks||{});
 const steps=['Basics','Class','Species','Background','Abilities','Training','Spells','Review'];
 function valid(at=step){const step=at;if(step===0)return draft.name.trim().length>=2;if(step===1)return !!c&&!!c.hit_die&&!prestige(c);if(step===2)return !!r&&(!r.referenceOnly||Number.isFinite(r.speed))&&(!subOptions.length||!!sub);if(step===3)return is35(draft)||!!bg||draft.ruleset==='custom'&&!!draft.background.trim();if(step===4){const scores=Object.values(draft.abilities);return (draft.method!=='d20'||!!draft.abilityRolls)&&scores.every(n=>Number.isInteger(n)&&n>=1&&n<=30)&&(draft.method!=='pointbuy'||scores.reduce((s,n)=>s+(cost[n]??100),0)<=27)&&(!(originBonus||halfElf)||(draft.bonusA&&draft.bonusB&&draft.bonusA!==draft.bonusB&&(draft.bonusMode!=='three'||!originBonus||draft.bonusC&&![draft.bonusA,draft.bonusB].includes(draft.bonusC))));}if(step===5)return languages.complete&&(!halfElf||(draft.bonusSkills||[]).length===2)&&(manual||draft.classSkills.length===skillLimit)&&(!(rules==='2014'&&['Cleric','Sorcerer','Warlock'].includes(draft.className))||draft.subclass.trim().length>1);if(step===6)return manual||draft.cantripIds.length===cantripLimit&&draft.spellIds.length===(spellLimit||0);return step===7?featurePlan.valid&&Array.from({length:7},(_,i)=>valid(i)).every(Boolean)&&(draft.feats||[]).every(f=>qualified(requirements(f,{...draft,abilityBonuses:bonuses,feats:(draft.feats||[]).filter(x=>x.id!==f.id)},f.prerequisiteConfirmations))):true;}
 function selectSpell(s){const list=s.level===0?'cantripIds':'spellIds',max=s.level===0?cantripLimit:spellLimit,key=keyOf(s);patch({spellChoices:{...draft.spellChoices,[key]:s},[list]:draft[list].includes(key)?draft[list].filter(x=>x!==key):draft[list].length<max?[...draft[list],key]:draft[list]});}
 function finish(){if(!valid(7))return;let char={...blankCharacter(draft.name.trim()),...draft,id:uid(),abilityBonuses:bonuses,abilities:draft.abilities,autoArmor:!is35(draft)&&c.edition===rules,hitDie:`d${c.hit_die||8}`,speed:r.speed??30,traits:[...(r.traits||[]),...(sub?.traits||sub?.racial_traits||[]).map(t=>(r.edition==='2024'?modern.traits:traits14).find(x=>x.index===t.index)||t)].map(t=>({...t,description:t.description||t.desc?.join('\n\n')||'',source:r.name})),skillProf:Object.fromEntries([...bgSkills,...draft.classSkills,...(draft.bonusSkills||[])].map(n=>[n,true])),saveProf:Object.fromEntries((c.saving_throws||[]).map(a=>[a.index,true])),inventory:[],spells:Object.values(draft.spellChoices||{}).filter(s=>[...draft.cantripIds,...draft.spellIds].includes(keyOf(s))).map(s=>({...s,id:uid(),prepared:s.level===0||counts.mode!=='spellbook'||draft.spellIds.indexOf(keyOf(s))<counts.prepared})),resources:[],currency:{gp:0},conditions:[],exhaustion:0};
 const max=Math.max(1,(c.hit_die||8)+modifier(totals.con)+(draft.subrace==='Hill Dwarf'||rules==='2024'&&r.name==='Dwarf'?1:0));char.hp={max,current:max,temp:0};
 const gear=[...(c.starting_equipment||[]).map(x=>({id:uid(),name:x.equipment.name,equipmentIndex:x.equipment.index,qty:x.quantity||1})),...(c.starting_equipment_options||[]).flatMap((x,i)=>resolveEquipment(x,draft.gear[i]))];
 if(rules==='2024'){gear.push(...(bg?.equipment_options||[]).flatMap((x,i)=>resolveEquipment(x,draft.bgGear[i])));char.feats=[...(char.feats||[]),...(bg?.feat?[{...modern.feats.find(f=>f.index===bg.feat.index),id:uid(),name:bg.feat.name,level:1,source:bg.name}]:[])];}
 else if(!is35(draft)&&bg)gear.push(...(bg.equipment||'').split(',').filter(Boolean).map(name=>/^\s*\d+ gp\s*$/.test(name)?{id:uid(),name:'gp',qty:parseInt(name),money:true}:{id:uid(),name:name.trim(),qty:1}));
 char.currency.gp=gear.filter(x=>x.money).reduce((n,x)=>n+x.qty,0);char.inventory=[...(draft.inventory||[]),...gear.filter(x=>!x.money).map(x=>({...x,equipped:!is35(char)&&!!(equipment.find(e=>e.index===x.equipmentIndex)?.armor_class||equipment.find(e=>e.index===x.equipmentIndex)?.damage)}))];
 if(is35(char)){char.bab=legacyProgression(char).bab;char.skillRanks={};char.save35=legacyProgression(char);}
 char.ac=is35(char)?10+modifier(totals.dex):armorFor(char,totals);char.languages=languageRules.manual?(draft.manualLanguages||''):languages.names.join(', ');
 if(typeof char.languages!=='string')char.languages=char.languages.map(x=>x.name||x).join(', ');
 if(rules==='2014'&&draft.ruleset!=='custom')char=syncProgression(char,1);delete char.spellChoices;delete char.spellIds;delete char.cantripIds;delete char.gear;delete char.bgGear;char=applyFeatureChoices(char,null,draft.featurePicks||{});delete char.featurePicks;onFinish(normalizeAdvancement(char));}
 return <div className="creation-overlay" role="dialog" aria-modal="true" aria-label="Guided character setup" ref={shell}><div className="creation-shell"><aside className="creation-sidebar"><div className="creation-brand"><strong>Build your adventurer</strong></div><div className="creation-step-list">{steps.map((n,i)=><button type="button" className={`creation-step-item ${i===step?'is-current':''} ${i<step?'is-complete':''}`} key={n} disabled={i>step} onClick={()=>setStep(i)}><span>{i<step?'✓':i+1}</span><strong>{n}</strong></button>)}</div><button className="creation-cancel" onClick={onCancel}>Cancel</button></aside><section className="creation-content"><div className="creation-topbar"><strong>Step {step+1} of {steps.length} · {steps[step]}</strong><span>{draft.name||'New adventurer'}</span></div><div className="creation-scroll"><h2>{['Start your story','Choose your class','Choose your species or race','Where did you come from?','Shape your abilities','Training & starting gear','Build your spellbook','Ready for adventure'][step]}</h2>
 {step===0&&<><Field label="Character name"><input required aria-invalid={!draft.name.trim()} value={draft.name} onChange={e=>patch({name:e.target.value})} placeholder="Your adventurer’s name"/></Field><h3>Choose a ruleset</h3><div className="creation-grid two">{editions.map(([id,name,desc])=><button type="button" key={id} className={`creation-choice ${draft.ruleset===id?'is-selected':''}`} onClick={()=>patch({ruleset:id,className:'',classDefinition:null,race:'',raceDefinition:null,background:'',classSkills:[],bonusSkills:[],spellIds:[],cantripIds:[],bonusA:'',bonusB:'',subrace:'',subclass:''})}><strong>{name}</strong><p>{desc}</p></button>)}</div>{draft.ruleset==='custom'&&<Field label="Base mechanics"><select value={draft.mechanics} onChange={e=>patch({mechanics:e.target.value})}>{editions.filter(x=>x[0]!=='custom').map(([id,n])=><option key={id} value={id}>{n}</option>)}</select></Field>}{reference.loading&&<p role="status">Loading full DnD Tools references…</p>}{reference.error&&<p role="alert">{reference.error}</p>}<p className="l-muted">Start at level 1, then use Level up. Custom mode unlocks all bundled and imported classes, races and spells. Mixing editions needs DM rulings.</p></>}
 {step===1&&<><Picks kind="class" options={classList} value={c&&keyOf(c)} onChange={x=>patch({className:x.name,classDefinition:x,classSkills:[],gear:{},spellIds:[],cantripIds:[],subclass:''})}/>{c?.referenceOnly&&<><p className="l-notice">This is a source reference. Enter its hit die from the book; class prerequisites and progression need your review.</p><Field label="Reference class hit die"><select value={c.hit_die||''} onChange={e=>patch({classDefinition:{...c,hit_die:Number(e.target.value)}})}><option value="">Choose hit die</option>{[4,6,8,10,12].map(n=><option key={n} value={n}>d{n}</option>)}</select></Field><a href={c.sourceUrl} target="_blank" rel="noreferrer">Read class source</a></>}{c&&<ClassProgression char={draft} onChange={patch} score={totals[draft.castingAbility||({Bard:'cha',Cleric:'wis',Druid:'wis',Paladin:'cha',Ranger:'wis',Sorcerer:'cha',Warlock:'cha',Wizard:'int'}[draft.className])]||10}/>} {c&&<details className="feature-detail"><summary>{c.name} details{c.prestige?' · check entry prerequisites with your DM':''}</summary><p className="preserve-lines">{c.description}</p></details>}</>}
 {step===2&&<><Picks kind="race" options={raceList} value={r&&keyOf(r)} onChange={x=>patch({race:x.name,raceDefinition:x,subrace:'',bonusA:'',bonusB:'',bonusC:''})}/>{r?.referenceOnly&&<><Field label="Reference race speed (ft.)"><input type="number" min="0" max="300" value={r.speed??''} onChange={e=>patch({raceDefinition:{...r,speed:Math.max(0,Math.min(300,Number(e.target.value)))}})}/></Field><a href={r.sourceUrl} target="_blank" rel="noreferrer">Read race source</a><p>Record racial ability adjustments using Enter scores or on your sheet.</p></>}{subOptions.length>0&&<Field label="Lineage or subrace"><select value={draft.subrace} onChange={e=>patch({subrace:e.target.value})}><option value="">Choose a lineage</option>{subOptions.map(s=><option key={s.index}>{s.name}</option>)}</select></Field>}{r&&<details className="feature-detail"><summary>Species traits</summary>{r.traits?.map((t,i)=><p key={i}><strong>{t.name}</strong> {t.description||t.desc?.join(' ')}</p>)}</details>}</>}
 {step===3&&(is35(draft)?<><p>3.5 does not grant 5e background packages. Record your origin here; it won’t add 5e skills or equipment.</p><Field label="Background or origin"><input value={draft.background} onChange={e=>patch({background:e.target.value})}/></Field></>:<><div className="creation-grid three">{(rules==='2024'?modern.backgrounds:Object.entries(BACKGROUND_DATA).map(([name,b])=>({name,...b}))).map(b=><button key={b.name} type="button" className={`creation-choice ${draft.background===b.name?'is-selected':''}`} onClick={()=>patch({background:b.name,classSkills:[],bonusA:'',bonusB:'',bonusC:''})}><span className="creation-choice-title">{b.name}</span><small>{b.skills||b.proficiencies?.map(x=>x.name).join(' · ')}</small></button>)}</div>{draft.ruleset==='custom'&&<Field label="Custom background"><input value={draft.background} onChange={e=>patch({background:e.target.value})}/></Field>}</>)}
 {step===4&&<><div className="l-toolbar">{['standard','pointbuy','custom','d20'].map(m=><button type="button" className={`l-button ${draft.method===m?'primary':''}`} key={m} onClick={()=>patch({method:m,abilityRolls:undefined,abilities:m==='standard'?basicScores:m==='pointbuy'?Object.fromEntries(ABILITIES.map(a=>[a.key,8])):draft.abilities})}>{m==='standard'?'Standard array':m==='pointbuy'?'27-point buy':m==='d20'?'Roll d20 scores':'Enter scores'}</button>)}</div>{draft.method==='d20'&&<div className="l-notice"><p>Homebrew ability method: roll one d20 for each ability (1–20), then apply your normal bonuses. Use this method if your table allows it.</p><button type="button" className="l-button primary" onClick={()=>{const rolls=Object.fromEntries(ABILITIES.map(a=>[a.key,onRoll('1d20',`${a.label} ability score`,{inline:true,mode:'normal'}).total]));patch({abilities:rolls,abilityRolls:rolls});}}>Roll all six d20s</button>{draft.abilityRolls&&<p role="status">Rolled: {ABILITIES.map(a=>`${a.label} ${draft.abilityRolls[a.key]}`).join(' · ')}</p>}</div>}<div className="ability-builder">{ABILITIES.map(a=><Field key={a.key} label={`${a.label} · total ${totals[a.key]} (${modifier(totals[a.key])>=0?'+':''}${modifier(totals[a.key])})`}>{draft.method==='standard'?<select value={draft.abilities[a.key]} onChange={e=>{const val=+e.target.value,other=Object.keys(draft.abilities).find(k=>k!==a.key&&draft.abilities[k]===val);patch({abilities:{...draft.abilities,...(other?{[other]:draft.abilities[a.key]}:{}),[a.key]:val}});}}>{Object.values(basicScores).map(n=><option key={n}>{n}</option>)}</select>:<input type="number" readOnly={draft.method==='d20'} min={draft.method==='pointbuy'?8:1} max={draft.method==='pointbuy'?15:30} value={draft.abilities[a.key]} onChange={e=>patch({abilities:{...draft.abilities,[a.key]:Number(e.target.value)}})}/>}</Field>)}</div>{draft.method==='pointbuy'&&<p>Points used: {Object.values(draft.abilities).reduce((s,n)=>s+(cost[n]??0),0)} / 27</p>}{(originBonus||halfElf)&&<><h3>{originBonus?'Background ability increases':'Half-Elf ability increases'}</h3>{originBonus&&<Field label="Ability increase method"><select value={draft.bonusMode} onChange={e=>patch({bonusMode:e.target.value,bonusA:'',bonusB:'',bonusC:''})}><option value="two">+2 to one, +1 to another</option><option value="three">+1 to three different abilities</option></select></Field>}<div className="form-grid">{['bonusA','bonusB',...(originBonus&&draft.bonusMode==='three'?['bonusC']:[])].map((key,i)=><Field key={key} label={`Ability increase ${i+1}`}><select value={draft[key]} onChange={e=>patch({[key]:e.target.value})}><option value="">Choose ability</option>{ABILITIES.filter(a=>halfElf?a.key!=='cha':!bg?.ability_scores||bg.ability_scores.some(x=>x.index===a.key)).map(a=><option key={a.key} value={a.key}>{a.label}</option>)}</select></Field>)}</div></>}</>}
 {step===5&&<>{manual?<p className="l-notice">3.5 skill ranks, prerequisites, multiclass progression, psionic power points and cross-edition conversions require your input. Spell slots and casting ability can be set in the spellbook.</p>:<><h3>Class skills · choose {skillLimit}</h3><div className="skill-picker-grid">{skillOptions.map(n=><button type="button" key={n} className={`skill-pill ${draft.classSkills.includes(n)?'is-selected':''}`} disabled={bgSkills.includes(n)} onClick={()=>patch({classSkills:draft.classSkills.includes(n)?draft.classSkills.filter(x=>x!==n):draft.classSkills.length<skillLimit?[...draft.classSkills,n]:draft.classSkills})}>{draft.classSkills.includes(n)?'✓ ':''}{n}</button>)}</div><p>Background skills: {bgSkills.join(', ')||'None'}</p></>}{rules==='2014'&&['Cleric','Sorcerer','Warlock'].includes(draft.className)&&<Field label="Subclass name"><input list="setup-subclass" value={draft.subclass} onChange={e=>patch({subclass:e.target.value})}/><datalist id="setup-subclass">{subclasses.filter(s=>s.class.name===draft.className).map(s=><option key={s.index} value={s.name}/>)}</datalist></Field>}{halfElf&&<><h3>Half-Elf bonus skills · choose 2</h3><div className="skill-picker-grid">{SKILLS.map(([n])=><button key={n} type="button" className={`skill-pill ${(draft.bonusSkills||[]).includes(n)?'is-selected':''}`} disabled={[...bgSkills,...draft.classSkills].includes(n)} onClick={()=>patch({bonusSkills:(draft.bonusSkills||[]).includes(n)?draft.bonusSkills.filter(x=>x!==n):(draft.bonusSkills||[]).length<2?[...(draft.bonusSkills||[]),n]:draft.bonusSkills})}>{(draft.bonusSkills||[]).includes(n)?'✓ ':''}{n}</button>)}</div></>}<LanguageChoices draft={draft} intelligence={totals.int} patch={patch}/><h3>Class equipment</h3>{(c?.starting_equipment_options||[]).map((choice,i)=><EquipmentChoice key={i} choice={choice} value={draft.gear[i]} onChange={v=>patch({gear:{...draft.gear,[i]:v}})}/>)}{rules==='2024'&&(bg?.equipment_options||[]).map((choice,i)=><EquipmentChoice key={`bg${i}`} choice={choice} value={draft.bgGear[i]} onChange={v=>patch({bgGear:{...draft.bgGear,[i]:v}})}/>)}<Field label="Feature choices and DM rulings"><textarea rows={3} value={draft.notes} onChange={e=>patch({notes:e.target.value})} placeholder="Record choices such as Divine Order, weapon mastery, bonus skills, or homebrew adjustments."/></Field></>}
 {step===6&&<><p className="l-notice">{manual?'Custom spell selection: confirm limits with your class source and DM.':`Level 1 ${draft.className}: ${cantripLimit} cantrips and ${spellLimit||0} ${counts.mode==='known'?'known spells':counts.mode==='spellbook'?'spells in your spellbook':'prepared spells'}. Spell slots limit casts between rests; they do not change how many spells you can learn.`}</p><p>Choose from the list; click a spell’s name to read its details. C = concentration, R = ritual.</p>{(cantripLimit>0)&&<SpellPicker label={is35(draft)?'Level 0 spells':'Cantrips'} spells={spells.filter(s=>s.level===0)} selected={draft.cantripIds} limit={cantripLimit} onToggle={selectSpell}/>} {spellLimit>0&&<SpellPicker label="Starting spells" spells={spells.filter(s=>s.level!==0)} selected={draft.spellIds} limit={spellLimit} onToggle={selectSpell}/>} {!cantripLimit&&!spellLimit&&<p>Your class doesn’t cast spells at level 1. Continue to review.</p>}</>}
 {step===7&&<><div className="review-hero"><h3>{draft.name}</h3><p>{editionName(draft.ruleset)} · {draft.race} {draft.className} · {draft.background||'Unwritten origin'}</p></div><div className="review-grid">{ABILITIES.map(a=><div className="review-stat" key={a.key}><span>{a.label}</span><strong>{totals[a.key]}</strong></div>)}</div><ClassFeatureChoices plan={featurePlan} picks={draft.featurePicks||{}} onChange={featurePicks=>patch({featurePicks})}/><CatalogItems char={draft} onAdd={item=>patch({inventory:[...(draft.inventory||[]),item]})}/>{(draft.inventory||[]).map(item=><div key={item.id}>{item.name}<button className="l-button" onClick={()=>patch({inventory:draft.inventory.filter(x=>x.id!==item.id)})}>Remove {item.name}</button></div>)}<FeatChoices char={{...draft,abilityBonuses:bonuses}} patch={patch} homebrew={customEntries} editable/><p>{draft.classSkills.length} class skills · {draft.spellIds.length+draft.cantripIds.length} spells selected</p><p>Languages: {languageRules.manual?draft.manualLanguages||'Not recorded':languages.names.join(', ')}</p><p>Traits, selected spells, gear and ability bonuses will be saved to the sheet. Supported feature choices are collected above. Record other feature effects in your notes and resource counters.</p></>}
 </div><div className="creation-footer"><button type="button" className="creation-secondary" onClick={()=>step?setStep(step-1):onCancel()}>{step?'Back':'Cancel'}</button><span className="creation-footer-status" role="status">{!valid()?'Complete the required choices above to continue.':''}</span><button type="button" className="creation-primary" disabled={!valid()} onClick={()=>step===7?finish():setStep(step+1)}>{step===7?'Create Character':'Continue'}</button></div></section></div></div>;
}
