import React, {useState} from 'react';
import {validPack, editions, editionName} from './lib/editions';

export default function Homebrew({entries, onChange}) {
  const [draft,setDraft]=useState({category:'spell',edition:'custom',name:'',description:'',level:1,classes:[],hit_die:8,speed:30});
  const [error,setError]=useState('');
  const patch=v=>setDraft({...draft,...v});
  function add(value){try{const added=validPack(value);onChange([...entries,...added]);setError('');return true;}catch(e){setError(e.message);return false;}}
  async function importFile(e){const file=e.target.files?.[0];if(!file)return;try{if(file.size>5_000_000)throw Error('Use a JSON file smaller than 5 MB.');add(JSON.parse(await file.text()));}catch(err){setError(err.message);}e.target.value='';}
  function download(){const url=URL.createObjectURL(new Blob([JSON.stringify({entries},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='dnd-homebrew.json';a.click();URL.revokeObjectURL(url);}
  return <section className="l-panel"><h2>Homebrew workshop</h2><p>Create options for your characters, or import a JSON pack. Custom characters can choose content from every edition. Rules and prerequisites remain subject to your table’s decisions.</p><div className="l-toolbar"><label className="l-field"><span>Import JSON pack</span><input type="file" accept=".json,application/json" onChange={importFile}/></label><button className="l-button" disabled={!entries.length} onClick={download}>Export homebrew</button></div><details><summary>JSON pack format</summary><pre>{JSON.stringify([{category:'spell',edition:'custom',name:'Example spell',description:'Describe the effect.',level:1,classes:['Wizard']}],null,2)}</pre><p>Categories: class, race, spell, feat, trait. Editions: 2014, 2024, 3.5, custom. Spells require a level and classes array. Classes may include hit_die; races may include speed and bonuses.</p></details>
  <form onSubmit={e=>{e.preventDefault();if(add([draft]))patch({name:'',description:''});}}><div className="form-grid"><label className="l-field"><span>Category</span><select aria-label="Category" value={draft.category} onChange={e=>patch({category:e.target.value})}>{['class','race','spell','feat','trait'].map(k=><option key={k}>{k}</option>)}</select></label><label className="l-field"><span>Edition</span><select aria-label="Edition" value={draft.edition} onChange={e=>patch({edition:e.target.value})}>{editions.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label><label className="l-field"><span>Name</span><input required maxLength={150} value={draft.name} onChange={e=>patch({name:e.target.value})}/></label>
  {draft.category==='spell'&&<><label className="l-field"><span>Spell level</span><input type="number" min="0" max="9" value={draft.level} onChange={e=>patch({level:Number(e.target.value)})}/></label><label className="l-field"><span>Classes (comma separated)</span><input value={draft.classes.join(', ')} onChange={e=>patch({classes:e.target.value.split(',').map(s=>s.trim())})}/></label></>}
  {draft.category==='class'&&<label className="l-field"><span>Hit die</span><select value={draft.hit_die} onChange={e=>patch({hit_die:Number(e.target.value)})}>{[4,6,8,10,12].map(n=><option key={n} value={n}>d{n}</option>)}</select></label>}
  {draft.category==='race'&&<label className="l-field"><span>Speed (ft.)</span><input type="number" min="0" max="300" value={draft.speed} onChange={e=>patch({speed:Number(e.target.value)})}/></label>}</div><label className="l-field"><span>Description and rules</span><textarea required rows={4} maxLength={30000} value={draft.description} onChange={e=>patch({description:e.target.value})}/></label><button className="l-button primary">Save homebrew entry</button></form>{error&&<p role="alert">{error}</p>}
  <h3>{entries.length} saved entries</h3>{entries.map(e=><details className="feature-detail" key={e.id}><summary>{e.name} · {e.category} · {editionName(e.edition)}</summary><p className="preserve-lines">{e.description}</p><button className="l-button danger" onClick={()=>onChange(entries.filter(x=>x.id!==e.id))}>Remove from workshop</button></details>)}</section>;
}
