import React,{useState} from 'react';
import {preparationState,canPrepareInSlot,prepareLegacySpells} from './lib/legacyPreparation';
import {legacyChoices,legacyChoiceKey} from './lib/legacyCastingChoices';

const label=slot=>`${slot.pool==='domain'?'Domain':slot.pool==='specialist'?'Specialist':'Standard'} level ${slot.level} slot ${slot.index+1}`;
export default function LegacyPreparation({model,pools,spells,accessFor,patch}){
 const [mode,setMode]=useState(''),[choices,setChoices]=useState({}),[error,setError]=useState('');
 const slots=preparationState(model,pools),byId=new Map(spells.map(s=>[s.id,s]));
 function start(value){setMode(value);setError('');setChoices(Object.fromEntries(slots.map(s=>[s.key,s.spent?'spent':s.spellId])));}
 function save(){try{patch(prepareLegacySpells(model,pools,choices,spells,accessFor,{daily:mode==='daily'}));setMode('');setError('');}catch(e){setError(e.message);}}
 return <section aria-label="Daily spell preparation" className="feature-detail"><h3>Prepared spell slots</h3>
 <p>Prepare each copy in its own slot, including level 0 spells. Casting spends that copy. A lower-level spell can use a higher slot without increasing its spell level or save DC.</p>
 {['Cleric','Cloistered Cleric'].includes(model.className)&&<label className="l-field"><span>Spontaneous conversion</span><select aria-label="Spontaneous conversion" value={legacyChoices(model).spontaneous||''} onChange={e=>patch({legacyCastingChoices:{...model.legacyCastingChoices,[legacyChoiceKey(model)]:{...legacyChoices(model),spontaneous:e.target.value}}})}><option value="">Choose according to deity and alignment</option><option value="cure" disabled={/evil/i.test(model.alignment||'')}>Cure spells</option><option value="inflict" disabled={/good/i.test(model.alignment||'')}>Inflict spells</option></select><small>Choose at character creation; later edits are setup corrections. Deity alignment may further restrict this choice. Add the desired cure or inflict spell to the spell list to cast it by converting a prepared standard slot.</small></label>}
 {model.className==='Druid'&&<p>Add a Summon Nature’s Ally spell to the spell list to cast it by converting a prepared standard slot of that level or higher.</p>}
 {!mode?<><div className="l-toolbar"><button className="l-button" onClick={()=>start('daily')}>Prepare daily spells</button><button className="l-button" onClick={()=>start('open')}>Fill open slots</button></div>
 <div className="form-grid">{slots.map(s=><p key={s.key}><strong>{label(s)}</strong>: {s.spent?'Spent':s.spellId?(byId.get(s.spellId)?.name||'Missing spell — prepare again'):'Open'}{!s.spent&&s.spellId&&byId.has(s.spellId)&&!canPrepareInSlot(model,byId.get(s.spellId),s,accessFor(byId.get(s.spellId)))?' · Ineligible — prepare again':''}</p>)}</div></>:<>
 <p>{mode==='daily'?'Complete this after your class’s required daily study or prayer. Wizards require 8 hours of qualifying rest. Leave slots for spells cast in the last 8 hours marked unavailable; they still count against today’s allowance. Rest alone does not prepare spells.':'After at least 15 minutes of suitable study or prayer, fill unused slots. Existing preparations and spent slots cannot be replaced until daily preparation.'}</p>
 <div className="form-grid">{slots.map(s=>{const candidates=spells.filter(spell=>canPrepareInSlot(model,spell,s,accessFor(spell))),value=choices[s.key]||'';return <label className="l-field" key={s.key}><span>{label(s)}</span><select aria-label={`Prepare ${label(s)}`} value={value} disabled={mode==='open'&&!!(s.spent||s.spellId)} onChange={e=>setChoices({...choices,[s.key]:e.target.value})}><option value="">Leave open</option><option value="spent">Unavailable — recent cast / spent</option>{value&&value!=='spent'&&!candidates.some(spell=>spell.id===value)&&<option value={value} disabled>{byId.get(value)?.name||'Missing spell'} — ineligible</option>}{candidates.map(spell=><option key={spell.id} value={spell.id}>{spell.name}</option>)}</select></label>;})}</div>
 {error&&<p role="alert">{error}</p>}<div className="l-toolbar"><button className="l-button primary" onClick={save}>{mode==='daily'?'Finish daily preparation':'Save open-slot preparation'}</button><button className="l-button" onClick={()=>setMode('')}>Cancel preparation</button></div></>}
 {!slots.length&&<p>This class has no available spell slots yet.</p>}</section>;
}
