import React,{useState} from 'react';
import {modifier,signed} from './lib/rules';
import {effectiveAbilities} from './CharacterManager';

export default function LegacyTraining({char,patch,roll}){
 const [name,setName]=useState(''),abilities=effectiveAbilities(char),skills=char.legacySkills||[];
 const number=e=>Math.max(-30,Math.min(100,Number(e.target.value)||0));
 return <><section className="l-panel"><h3>3.5 attacks & saves</h3><label className="l-field"><span>Base attack bonus</span><input type="number" value={char.bab||0} onChange={e=>patch({bab:number(e)})}/></label>{[['fort','Fortitude','con'],['ref','Reflex','dex'],['will','Will','wis']].map(([key,label,ability])=><div key={key} className="l-toolbar"><label className="l-field"><span>{label} base + misc.</span><input type="number" value={char.save35?.[key]||0} onChange={e=>patch({save35:{...char.save35,[key]:number(e)}})}/></label><button className="l-button" onClick={()=>roll(`1d20${signed((char.save35?.[key]||0)+modifier(abilities[ability]))}`,`${label} save`,{kind:'save'})}>Roll {signed((char.save35?.[key]||0)+modifier(abilities[ability]))}</button></div>)}<p className="l-muted">Base class saves are prefilled where available. Include racial, feat and item adjustments here.</p></section>
 <section className="l-panel"><h3>3.5 skill ranks</h3>{skills.map(s=><div className="legacy-skill" key={s.id}><strong>{s.name}</strong><label className="l-field"><span>Ability</span><select value={s.ability} onChange={e=>patch({legacySkills:skills.map(x=>x.id===s.id?{...x,ability:e.target.value}:x)})}>{Object.keys(abilities).map(a=><option key={a}>{a}</option>)}</select></label>{['ranks','misc'].map(k=><label className="l-field" key={k}><span>{k}</span><input type="number" step="0.5" value={s[k]} onChange={e=>patch({legacySkills:skills.map(x=>x.id===s.id?{...x,[k]:number(e)}:x)})}/></label>)}<button className="l-button" onClick={()=>roll(`1d20${signed(Math.floor(s.ranks)+s.misc+modifier(abilities[s.ability]))}`,`${s.name} check`,{kind:'check'})}>Roll</button><button className="l-button" aria-label={`Remove ${s.name}`} onClick={()=>patch({legacySkills:skills.filter(x=>x.id!==s.id)})}>×</button></div>)}<form className="l-toolbar" onSubmit={e=>{e.preventDefault();if(name.trim()){patch({legacySkills:[...skills,{id:crypto.randomUUID(),name:name.trim(),ability:'int',ranks:0,misc:0}]});setName('');}}}><label className="l-field"><span>Skill name</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Concentration"/></label><button className="l-button">Add skill</button></form><p className="l-muted">Track class and cross-class ranks, armor penalties and trained-only restrictions from your class reference. Half ranks count toward rank limits; round down when rolling.</p></section></>;
}
