import React,{useState} from 'react';
import {modifier,signed} from './lib/rules';
import {effectiveAbilities} from './CharacterManager';
import {legacyClassSkillStatus} from './lib/classIntegration';

const norm=value=>String(value||'').toLowerCase().replace(/[’']/g,"'").trim();
function ruleText(entry){
 const rule=entry?.rule||{};
 if(rule.mode==='choose_any')return `Choose any ${rule.count||0} class skills${rule.additional?.length?`, plus ${rule.additional.join(', ')}`:''}.`;
 if(rule.mode==='inherit_from_other_classes')return 'Skills that are class skills for another one of this character’s classes are class skills here too.';
 if(rule.mode==='inherit_from_previous_classes_or_race')return 'Class skills are inherited from previous classes or the base race as stated by the source.';
 return rule.text||'This class uses a source-defined class-skill rule.';
}
export default function LegacyTraining({char,patch,roll}){
 const [name,setName]=useState(''),abilities=effectiveAbilities(char),skills=char.legacySkills||[];
 const classSkillEntries=char.classSkills35||[],classSkillNames=[...new Set(classSkillEntries.map(entry=>entry.name))],dynamicRules=char.classSkillRules35||[],overrides=char.classSkillOverrides35||{};
 const number=e=>Math.max(-30,Math.min(100,Number(e.target.value)||0));
 return <><section className="l-panel"><h3>3.5 attacks & saves</h3><label className="l-field"><span>Base attack bonus</span><input type="number" value={char.bab||0} onChange={e=>patch({bab:number(e)})}/></label>{[['fort','Fortitude','con'],['ref','Reflex','dex'],['will','Will','wis']].map(([key,label,ability])=><div key={key} className="l-toolbar"><label className="l-field"><span>{label} base + misc.</span><input type="number" value={char.save35?.[key]||0} onChange={e=>patch({save35:{...char.save35,[key]:number(e)}})}/></label><button className="l-button" onClick={()=>roll(`1d20${signed((char.save35?.[key]||0)+modifier(abilities[ability]))}`,`${label} save`,{kind:'save'})}>Roll {signed((char.save35?.[key]||0)+modifier(abilities[ability]))}</button></div>)}<p className="l-muted">Base class saves are prefilled where available. Include racial, feat and item adjustments here.</p></section>
 <section className="l-panel"><h3>3.5 skill ranks</h3>{classSkillNames.length>0&&<details className="feature-detail"><summary>Class skills <span>{classSkillNames.length} source-derived</span></summary><p>{classSkillNames.join(', ')}</p></details>}{dynamicRules.length>0&&<details className="feature-detail"><summary>Class-skill rules <span>{dynamicRules.length}</span></summary>{dynamicRules.map(entry=><p key={entry.id}><strong>{entry.sourceClassName}:</strong> {ruleText(entry)}</p>)}</details>}{skills.map(s=>{const status=legacyClassSkillStatus(char,s.name),cap=status.rankCap;return <div className="legacy-skill" key={s.id}><div><strong>{s.name}</strong><small>{status.fixed?`Class skill · standard rank cap ${cap}`:status.manual?`Source-rule class skill · standard rank cap ${cap}`:dynamicRules.length?`Check source-defined class-skill rule · current cross-class cap ${cap}`:`Cross-class · standard rank cap ${cap}`}</small>{dynamicRules.length&&!status.fixed&&<label className="spell-picker-toggle"><input type="checkbox" aria-label={`${s.name} counts as class skill under source rule`} checked={status.manual} onChange={e=>patch({classSkillOverrides35:{...overrides,[norm(s.name)]:e.target.checked}})}/>Class skill under source rule</label>}</div><label className="l-field"><span>Ability</span><select value={s.ability} onChange={e=>patch({legacySkills:skills.map(x=>x.id===s.id?{...x,ability:e.target.value}:x)})}>{Object.keys(abilities).map(a=><option key={a}>{a}</option>)}</select></label>{['ranks','misc'].map(k=><label className="l-field" key={k}><span>{k}</span><input type="number" step="0.5" value={s[k]} onChange={e=>patch({legacySkills:skills.map(x=>x.id===s.id?{...x,[k]:number(e)}:x)})}/></label>)}<button className="l-button" onClick={()=>roll(`1d20${signed(Math.floor(s.ranks)+s.misc+modifier(abilities[s.ability]))}`,`${s.name} check`,{kind:'check'})}>Roll</button><button className="l-button" aria-label={`Remove ${s.name}`} onClick={()=>patch({legacySkills:skills.filter(x=>x.id!==s.id)})}>×</button></div>;})}<form className="l-toolbar" onSubmit={e=>{e.preventDefault();if(name.trim()){patch({legacySkills:[...skills,{id:crypto.randomUUID(),name:name.trim(),ability:'int',ranks:0,misc:0}]});setName('');}}}><label className="l-field"><span>Skill name</span><input list="legacy-class-skills" value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Concentration"/><datalist id="legacy-class-skills">{classSkillNames.filter(skill=>!skills.some(row=>norm(row.name)===norm(skill))).map(skill=><option key={skill} value={skill}/>)}</datalist></label><button className="l-button">Add skill</button></form><p className="l-muted">Class-skill status and standard rank caps are derived where the source provides a fixed list. You still choose how to spend skill points; source-specific exceptions and purchase costs remain under your control.</p></section></>;
}
