import React,{useEffect,useState} from 'react';
import {catalogs,useCatalogs} from './lib/referenceIndex';
import Dialog from './Dialog';
import Requirements from './Requirements';
export default function ReferenceCatalog({source='dndtools'}) {
 const [manifest,setManifest]=useState(null),[category,setCategory]=useState('spells'),[query,setQuery]=useState(''),[page,setPage]=useState(0),[error,setError]=useState(''),[detail,setDetail]=useState(null);
 const data=useCatalogs([`${source==='dndtools'?'3.5':'5e'}/${category}`]);
 useEffect(()=>{let active=true;setManifest(null);setError('');catalogs.manifest(source).then(m=>{if(active)setManifest(m);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[source]);
 const filtered=data.entries.filter(e=>e.name.toLowerCase().includes(query.trim().toLowerCase())),pages=Math.max(1,Math.ceil(filtered.length/30)),current=Math.min(page,pages-1);
 return <section aria-label={source==='dndtools'?'DnD Tools reference catalog':'Wikidot 5e catalog'}><p>Browse source records, mechanics and progression. Same-name entries from different books retain their own identity.</p>{manifest&&<div className="l-list-controls"><label className="l-field"><span>Reference category</span><select value={category} onChange={e=>{setCategory(e.target.value);setQuery('');setPage(0);}}>{manifest.categories.map(c=><option key={c.id} value={c.id}>{c.id} ({c.count.toLocaleString()})</option>)}</select></label><label className="l-field"><span>Search references</span><input value={query} onChange={e=>{setQuery(e.target.value);setPage(0);}}/></label></div>}
 {(error||data.error)&&<p role="alert">{error||data.error}<button className="l-button" onClick={data.retry}>Retry catalog</button></p>}{data.loading?<p role="status">Loading catalog…</p>:<><p aria-live="polite">{filtered.length.toLocaleString()} results</p>{data.entries.some(e=>e.integrityIssues.length>0)&&<p className="l-notice" role="alert">This category contains invalid source extracts. Affected records are marked incomplete and cannot be selected as verified rules.</p>}<div className="compendium-grid">{filtered.slice(current*30,current*30+30).map(e=><article key={e.catalogId}><a className="compendium-card" href={e.sourceUrl} target="_blank" rel="noreferrer"><span className="l-eyebrow">{e.contentType} · {e.sourceBook||e.source}</span><h3>{e.name}</h3><p>{e.integrityIssues.length?'Incomplete effect · source review needed':e.description.slice(0,170)}</p><small>{e.sourceId} · Open source ↗</small></a><button className="l-button" onClick={()=>setDetail(e)}>View {e.name}</button></article>)}</div><div className="l-toolbar"><button className="l-button" disabled={!current} onClick={()=>setPage(current-1)}>Previous</button><span>Page {current+1} of {pages}</span><button className="l-button" disabled={current+1>=pages} onClick={()=>setPage(current+1)}>Next</button></div></>}
 {detail&&<Dialog title={detail.name} wide onClose={()=>setDetail(null)}><p>{detail.sourceBook||detail.source} {detail.sourcePage&&`· page ${detail.sourcePage}`}</p>{detail.integrityIssues.length>0&&<p role="alert">Effect unavailable: the source extract failed integrity checks.</p>}<p className="preserve-lines">{detail.description}</p><dl>{Object.entries(detail.stats).filter(([,v])=>v!=null&&v!==''&&(!Array.isArray(v)||v.length)).map(([k,v])=><React.Fragment key={k}><dt>{k}</dt><dd>{typeof v==='object'?JSON.stringify(v):String(v)}</dd></React.Fragment>)}</dl><Requirements checks={(detail.prerequisites||[]).map((p,i)=>({id:i,text:p.text,status:'manual'}))}/>{detail.tables?.map((t,i)=><div className="progression-scroll" key={i}><table className="progression-table"><tbody>{t.map((r,j)=><tr key={j}>{r.map((v,k)=>j?<td key={k}>{v}</td>:<th key={k}>{v}</th>)}</tr>)}</tbody></table></div>)}<a href={detail.sourceUrl} target="_blank" rel="noreferrer">Read source</a></Dialog>}
 </section>;
}
